// Benchmark driver. Compiled once per worktree against that commit's own WebView replay sources.
// -D PLUGIN selects the e420ad65 (plugin envelope) API; otherwise the graft API.

import Foundation

// MARK: - Variant adapter

#if PLUGIN
typealias WVIn = WebViewReplayEnvelope
typealias WVOut = WebViewReplayEnvelope
typealias ChannelStates = [Int: WebViewReplayDocument]

final class Ingestor {
    let channelId: Int
    init(channelId: Int) { self.channelId = channelId }
    func ingest(_ body: String, receivedAt: TimeInterval) -> [WVIn] {
        WebViewReplayPayloadParser.envelopes(fromBridgeBody: body, channelId: channelId, receivedAt: receivedAt)
    }
    func parseOnly(_ body: String) -> Int { WebViewReplayPayloadParser.extractEvents(from: body)?.count ?? 0 }
}

func inBytes(_ e: WVIn) -> Int { e.innerJSON.count }

func buildChunk(pending: [WVIn], chunkStart: TimeInterval, nativeFullSnapshots: [TimeInterval], moves: [TimeInterval],
                channelId: Int, states: inout ChannelStates) -> [WVOut] {
    // e420 passes every native full snapshot in the chunk, the leading one included; mutations that
    // move the mount point are not an input to it.
    WebViewReplayChunkBuilder.build(pending: pending, nativeFullSnapshotTimestamps: nativeFullSnapshots,
                                    chunkStart: chunkStart, reemitChannels: [channelId], documents: &states)
}

func pieceJSON(_ e: WVOut) -> Data { e.encoded() }
func retainedBytes(_ s: ChannelStates) -> Int { s.values.reduce(0) { $0 + ($1.meta?.innerJSON.count ?? 0) + $1.full.innerJSON.count } }
func documentCopies(_ out: [WVOut]) -> Int { out.filter { $0.isDocument }.count }
#else
typealias WVIn = WebViewReplayEvent
typealias WVOut = WebViewReplayOutputEvent
typealias ChannelStates = [Int: WebViewReplayChannelState]

final class Ingestor {
    let channelId: Int
    let remapper: WebViewReplayRemapper
    init(channelId: Int) { self.channelId = channelId; remapper = WebViewReplayRemapper(channelId: channelId) }
    func ingest(_ body: String, receivedAt: TimeInterval) -> [WVIn] {
        guard let events = WebViewReplayPayloadParser.extractEvents(from: body), !events.isEmpty else { return [] }
        return remapper.translate(events, receivedAt: receivedAt)
    }
    func parseOnly(_ body: String) -> Int { WebViewReplayPayloadParser.extractEvents(from: body)?.count ?? 0 }
}

func inBytes(_ e: WVIn) -> Int { e.json.count }

func buildChunk(pending: [WVIn], chunkStart: TimeInterval, nativeFullSnapshots: [TimeInterval], moves: [TimeInterval],
                channelId: Int, states: inout ChannelStates) -> [WVOut] {
    // What recordWebViewMounts emits: a full snapshot mounts every visible iframe; a move is a
    // remove + add of the same node in one mutation, which reads as a single (re)mount.
    let transitions = (nativeFullSnapshots + moves).sorted().map {
        WebViewMountTransition(timestamp: $0, channelId: channelId, mounted: true)
    }
    return WebViewReplayChunkBuilder.build(pending: pending, mountTransitions: transitions, chunkStart: chunkStart, states: &states)
}

func pieceJSON(_ e: WVOut) -> Data { e.json }
func retainedBytes(_ s: ChannelStates) -> Int { s.values.reduce(0) { $0 + ($1.document?.json.count ?? 0) + $1.backlogBytes } }
func documentCopies(_ out: [WVOut]) -> Int { Set(out.compactMap { $0.graftGroup }).count }
#endif

// MARK: - Timing

func nowNs() -> UInt64 { clock_gettime_nsec_np(CLOCK_UPTIME_RAW) }

struct Stat: Codable { let median: Double; let p90: Double; let n: Int }

func measure(minIterations: Int = 15, minSeconds: Double = 0.75, _ body: () -> Void) -> Stat {
    for _ in 0..<3 { autoreleasepool { body() } }
    var samples = [Double]()
    let start = nowNs()
    while samples.count < minIterations || (Double(nowNs() - start) / 1e9 < minSeconds && samples.count < 500) {
        let t = nowNs()
        autoreleasepool { body() }
        samples.append(Double(nowNs() - t) / 1e6)
    }
    samples.sort()
    return Stat(median: samples[samples.count / 2], p90: samples[Int(Double(samples.count - 1) * 0.9)], n: samples.count)
}

var results = [[String: Any]]()
/// Every record is stamped with the build it came from (BuildInfo.swift, generated by build.sh).
func emit(_ record: [String: Any]) {
    results.append(record.merging(["variant": benchVariant, "branch": benchBranch, "rev": benchRev]) { a, _ in a })
}
func statDict(_ s: Stat) -> [String: Any] { ["median": s.median, "p90": s.p90, "n": s.n] }

// MARK: - Harvest (mirrors SessionReplayManager.mergeReplayChunk + encodeReplayChunk)

struct HarvestResult { let raw: Int; let gz: Int; let shed: Int; let pieces: Int }

func encodeChunk(native: NativeChunk, webView: [WVOut]) -> HarvestResult {
    var pieces = [WebViewReplayPayloadBudget.Piece]()
    pieces.reserveCapacity(native.events.count + webView.count)
    let anchor = min(2, native.events.count)
    for i in 0..<anchor { pieces.append(.init(event: .native(native.events[i]), json: native.json[i])) }
    var n = anchor, w = 0
    while n < native.events.count || w < webView.count {
        let takeNative = n < native.events.count && (w >= webView.count || native.events[n].base.timestamp <= webView[w].timestamp)
        if takeNative {
            pieces.append(.init(event: .native(native.events[n]), json: native.json[n])); n += 1
        } else {
            pieces.append(.init(event: .webView(webView[w]), json: pieceJSON(webView[w]))); w += 1
        }
    }
    let budgeted = WebViewReplayPayloadBudget.enforce(pieces, limit: 1_000_000) { try? $0.gzipped().count }
    let json = WebViewReplayPayloadBudget.joinedJSON(budgeted.pieces)
    let gz = (try? json.gzipped().count) ?? -1
    return HarvestResult(raw: json.count, gz: gz, shed: budgeted.shedCount, pieces: budgeted.pieces.count)
}

// MARK: - Ingest microbenchmarks

func runIngest() {
    for agentShape in [true, false] {
    for size in PageSize.allCases {
        let gen = PageGenerator(seed: 42)
        let t0: TimeInterval = 1_790_000_000_000
        let doc = gen.document(nodes: size.nodes)
        let docBody = bridgeBody([metaEvent(at: t0), fullSnapshotEvent(doc, at: t0)], agentShape: agentShape)
        let mut5 = bridgeBody(gen.incrementals(start: t0 + 10, seconds: 5), agentShape: agentShape)
        let mut1 = bridgeBody(gen.incrementals(start: t0 + 5010, seconds: 1), agentShape: agentShape)

        let ingestor = Ingestor(channelId: 7)
        let docOut = ingestor.ingest(docBody, receivedAt: t0)          // also sets the graft's ID base
        let mut5Out = ingestor.ingest(mut5, receivedAt: t0)

        let parseDoc = measure { _ = ingestor.parseOnly(docBody) }
        let ingestDoc = measure {
            let i = Ingestor(channelId: 7)
            _ = i.ingest(docBody, receivedAt: t0)
        }
        let parseMut = measure(minIterations: 30) { _ = ingestor.parseOnly(mut5) }
        let ingestMut5 = measure(minIterations: 30) { _ = ingestor.ingest(mut5, receivedAt: t0) }
        let ingestMut1 = measure(minIterations: 30) { _ = ingestor.ingest(mut1, receivedAt: t0) }

        emit(["kind": "ingest", "shape": agentShape ? "agent" : "rrweb", "size": size.rawValue, "nodes": size.nodes,
              "docBridgeBytes": docBody.utf8.count, "docOutBytes": docOut.reduce(0) { $0 + inBytes($1) },
              "mut5BridgeBytes": mut5.utf8.count, "mut5OutBytes": mut5Out.reduce(0) { $0 + inBytes($1) },
              "mut5Events": mut5Out.count,
              "parseDoc": statDict(parseDoc), "ingestDoc": statDict(ingestDoc),
              "parseMut5": statDict(parseMut), "ingestMut5": statDict(ingestMut5), "ingestMut1": statDict(ingestMut1)])
        FileHandle.standardError.write("ingest \(agentShape ? "agent" : "rrweb") \(size.rawValue) done\n".data(using: .utf8)!)
    }
    }
}

// MARK: - Harvest timelines

struct Scenario {
    let name: String
    let batchSeconds: Double
    let freshDocEachChunk: Bool
    let extraFullSnapshotOffsets: [Double]
    let moveOffsets: [Double]
    /// Bridge bodies carry the agent's `__serialized` copies (observation agent) or not (rrweb recorder).
    var agentShape = true
}

let scenarios = [
    Scenario(name: "baseline", batchSeconds: 5, freshDocEachChunk: false, extraFullSnapshotOffsets: [], moveOffsets: []),
    Scenario(name: "+3 native FS/chunk", batchSeconds: 5, freshDocEachChunk: false, extraFullSnapshotOffsets: [15, 30, 45], moveOffsets: []),
    Scenario(name: "+10 iframe moves/chunk", batchSeconds: 5, freshDocEachChunk: false, extraFullSnapshotOffsets: [],
             moveOffsets: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
    Scenario(name: "rrweb capture (1s batches + fresh doc/chunk)", batchSeconds: 1, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [], moveOffsets: [], agentShape: false),
    Scenario(name: "rrweb capture +3 native FS/chunk", batchSeconds: 1, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [15, 30, 45], moveOffsets: [], agentShape: false),
    Scenario(name: "rrweb capture +10 iframe moves/chunk", batchSeconds: 1, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [], moveOffsets: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50], agentShape: false),
    // The observation agent asked for a FullSnapshot after every native harvest: its changes still
    // arrive on the 5s harvest interval, but the snapshot is harvested immediately.
    Scenario(name: "agent+snapshot capture (5s batches + fresh doc/chunk)", batchSeconds: 5, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [], moveOffsets: []),
    Scenario(name: "agent+snapshot capture +3 native FS/chunk", batchSeconds: 5, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [15, 30, 45], moveOffsets: []),
    Scenario(name: "agent+snapshot capture +10 iframe moves/chunk", batchSeconds: 5, freshDocEachChunk: true,
             extraFullSnapshotOffsets: [], moveOffsets: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
]

func runTimeline(size: PageSize, scenario: Scenario, chunks: Int = 6) {
    let channelId = 7
    let gen = PageGenerator(seed: 99)
    let ingestor = Ingestor(channelId: channelId)
    var states = ChannelStates()
    let base: TimeInterval = 1_790_000_000_000

    for k in 0..<chunks {
        let start = base + Double(k) * 60_000
        var bodies = [String]()
        var t = start
        if k == 0 || scenario.freshDocEachChunk {
            let at = start + (k == 0 ? 1_500 : 1_000)
            bodies.append(bridgeBody([metaEvent(at: at), fullSnapshotEvent(gen.document(nodes: size.nodes), at: at)],
                                     agentShape: scenario.agentShape))
            t = at
        }
        while t < start + 60_000 - 1 {
            let len = min(scenario.batchSeconds, (start + 60_000 - t) / 1000)
            bodies.append(bridgeBody(gen.incrementals(start: t, seconds: len), agentShape: scenario.agentShape))
            t += len * 1000
        }
        let pending = bodies.flatMap { ingestor.ingest($0, receivedAt: start) }
        let fullSnapshots = [start] + scenario.extraFullSnapshotOffsets.map { start + $0 * 1000 }
        let moves = scenario.moveOffsets.map { start + $0 * 1000 }
        let native = nativeChunk(start: start, seconds: 60, extraFullSnapshots: Array(fullSnapshots.dropFirst()))

        let before = states
        let buildStat = measure(minIterations: 10, minSeconds: 0.3) {
            var s = before
            _ = buildChunk(pending: pending, chunkStart: start, nativeFullSnapshots: fullSnapshots, moves: moves, channelId: channelId, states: &s)
        }
        let webView = buildChunk(pending: pending, chunkStart: start, nativeFullSnapshots: fullSnapshots, moves: moves, channelId: channelId, states: &states)
        var harvest: HarvestResult!
        let encodeStat = measure(minIterations: 5, minSeconds: 0.3) { harvest = encodeChunk(native: native, webView: webView) }
        let joined = WebViewReplayPayloadBudget.joinedJSON(webView.map { .init(event: .webView($0), json: pieceJSON($0)) })
        let gzipOnce = measure(minIterations: 5, minSeconds: 0.2) { _ = try? joined.gzipped() }

        emit(["kind": "harvest", "size": size.rawValue, "scenario": scenario.name, "chunk": k,
              "pendingEvents": pending.count, "webViewEvents": webView.count, "documentCopies": documentCopies(webView),
              "webViewRawBytes": webView.reduce(0) { $0 + pieceJSON($1).count },
              "chunkRawBytes": harvest.raw, "chunkGzBytes": harvest.gz, "shed": harvest.shed,
              "retainedBytes": retainedBytes(states),
              "build": statDict(buildStat), "encode": statDict(encodeStat), "gzipWebViewPart": statDict(gzipOnce)])
    }
    FileHandle.standardError.write("timeline \(size.rawValue) / \(scenario.name) done\n".data(using: .utf8)!)
}

// MARK: - Peak memory of one document ingest (run in its own process)

func maxRSS() -> Int {
    var usage = rusage()
    getrusage(RUSAGE_SELF, &usage)
    return Int(usage.ru_maxrss)   // bytes on Darwin
}

/// `mem <dir> [size] [agent|rrweb]` -- run one size and shape per process so peak RSS is its own.
func runMemory(fixtureDir: String) {
    let shape = CommandLine.arguments.count > 4 ? CommandLine.arguments[4] : "agent"
    for size in PageSize.allCases {
        let path = "\(fixtureDir)/\(size.rawValue)-doc\(shape == "agent" ? "" : "-" + shape).json"
        if CommandLine.arguments.count > 3, CommandLine.arguments[3] != size.rawValue { continue }
        let body = try! String(contentsOfFile: path, encoding: .utf8)
        _ = body.utf8.count
        let baseline = maxRSS()
        let ingestor = Ingestor(channelId: 7)
        let out = ingestor.ingest(body, receivedAt: 1)
        let peak = maxRSS()
        emit(["kind": "memory", "shape": shape, "size": size.rawValue, "bridgeBytes": body.utf8.count,
              "peakDeltaBytes": peak - baseline, "outBytes": out.reduce(0) { $0 + inBytes($1) }])
    }
}

func writeFixtures(dir: String) {
    try? FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
    for size in PageSize.allCases {
        let gen = PageGenerator(seed: 42)
        let events = [metaEvent(at: 1_790_000_000_000), fullSnapshotEvent(gen.document(nodes: size.nodes), at: 1_790_000_000_000)]
        try! bridgeBody(events).write(toFile: "\(dir)/\(size.rawValue)-doc.json", atomically: true, encoding: .utf8)
        try! bridgeBody(events, agentShape: false).write(toFile: "\(dir)/\(size.rawValue)-doc-rrweb.json", atomically: true, encoding: .utf8)
    }
}

// MARK: - Main

let mode = CommandLine.arguments.dropFirst().first ?? "all"
switch mode {
case "gen":
    writeFixtures(dir: CommandLine.arguments[2])
case "mem":
    runMemory(fixtureDir: CommandLine.arguments[2])
case "ingest":
    runIngest()
case "harvest":
    for size in PageSize.allCases {
        let filter = CommandLine.arguments.count > 2 ? CommandLine.arguments[2] : ""
        for scenario in scenarios where (size != .small || scenario.name == "baseline") &&
            (filter.isEmpty || scenario.name.hasPrefix(filter)) {
            runTimeline(size: size, scenario: scenario)
        }
    }
default:
    runIngest()
}
let out = try! JSONSerialization.data(withJSONObject: results, options: [.prettyPrinted, .sortedKeys])
FileHandle.standardOutput.write(out)
