# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins

import "TestFastfile"
import "UtilityFastfile"
import "FrameworkFastfile"
import "BuildFastfile"
import "VersionFastfile"
import "ConstantsFastfile"

default_platform(:ios)

platform :ios do

  desc "Build NewRelic.XCFramework for all platforms"
  lane :buildFramework do

    deleteBuildArtifacts

    buildIOS
    buildTVOS
    buildMacOS

    internalOutputXCFramework
  end

  desc "Run Tests for iOS/tvOS and Build NewRelic.XCFramework for all platforms"
  lane :testAndBuild do
    
    puts "Running tests 🧪 for iOS and tvOS"
    
    runTests
    
    puts "Successfully ran tests. 🚀 Building NewRelic.xcframework for all platforms"

    buildAndZip
  end

lane :buildAndZip do 
    # Set the version string based on the current branch and PR.
    generateVersion
    
    buildFramework

    zipFramework
end

  # zip cocoapods/LICENSE, cocoapods/README, cocoapods/README.md, and NewRelic.xcframework 
  # => into NewRelic_XCFramework_Agent_Version.zip
  lane :zipFramework do
    version = File.read("build_version")
    Dir.chdir("..") do
        sh("mv NewRelic.xcframework cocoapods")
        Dir.chdir("cocoapods") do
            sh("zip -r -y ../#{version} LICENSE README README.md NewRelic.xcframework")
        end
    end
  end

  # DEBUG LANES

  desc "Build NewRelic.XCFramework for iOS Only"
  lane :buildFrameworkIOSOnly do

    deleteBuildArtifacts

    buildIOS

    internalOutputXCFrameworkIOSOnly
  end
end
