//
//  W3CTraceState.mm
//  Agent
//
//  Created by Matt Aken on 12/23/20.
//  Copyright © 2020 New Relic. All rights reserved.
//

#import "W3CTraceState.h"

@implementation W3CTraceState

NSString *INVALID_TRACE_ID = @"00000000000000000000000000000000";
NSString *INVALID_PARENT_ID = @"0000000000000000";


+ (NSString *) trustedAccountKeyFor:(AccountType) trustedAccount {
    switch (trustedAccount) {
        case NRTraceContext:
            return @"@nr";
        default:
            return @"";
    }
}

+ (NSString *) getVersion {
    return @"0";
}
+ (NSString *) getParentType {
    return @"2";
}
+ (NSString *) getSampled {
    return @"0";
}
+ (NSString *) getPriority {
    return @"";
}
+ (NSString *) headerFromContext:(TraceContext*) traceContext {
    NSString *formatStr = @"%@=%@-%@-%@-%@-%@-%@-%@-%@-%lld";

    // do not base64 encode
    NSString *headerString = [NSString stringWithFormat:formatStr,
                              [W3CTraceState trustedAccountKeyFor: traceContext.trustedAccount],
                              [W3CTraceState getVersion],
                              [W3CTraceState getParentType],
                              traceContext.accountId,
                              traceContext.appId,
                              traceContext.spanId,
                              traceContext.transactionId,
                              [W3CTraceState getSampled],
                              [W3CTraceState getPriority],
                              traceContext.timestamp];
    
    return headerString;
}

- (void) setNewRelicDefaults {
    _version = 0;
    _parentType = 2;  // DONE Mobile
    _accountId = @""; // DONE payload
    _appId = @"";     // DONE payload
    
    // should be empty here right?? (generated parentId, in Android). make sure this can have dashes - ask Cameron
    _spanId = @""; // generated by Context
    _transactionId = @""; // should be unused
    _sampled = 0;     // DONE trace never sampled by parent
    _priority = @"";  // DONE looks like android is leaving this blank
    _timestamp = 0;
}
- (id) init {
    [self setNewRelicDefaults];
    return self;
}

- (id) initWithPayload: (std::unique_ptr<NewRelic::Connectivity::Payload>&)payload {
    [self setNewRelicDefaults];
    
    self.accountId = [NSString stringWithCString:payload->getAccountId().c_str()
                               encoding:NSUTF8StringEncoding];
    self.appId = [NSString stringWithCString:payload->getAppId().c_str()
                                    encoding:NSUTF8StringEncoding];
    /*self.spanId = [NSString stringWithCString:payload->getTraceId().c_str()
                                     encoding:NSUTF8StringEncoding];
    self.transactionId = [NSString stringWithCString:payload->getTraceId().c_str()
                                            encoding:NSUTF8StringEncoding];*/
    self.timestamp = payload->getTimestamp();
    return self;
}
@end
