name: CI
on: push

jobs:
  test:
    # runs-on: will be set to macos-latest when running on actual GHA. 
    # *** runs-on: ubuntu-latest is used when running via act on mac os. ***
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1'

    - name: Install gems
      run: bundle install

    # - name: Run iOS tests using only Xcode build.
    #   run: xcodebuild -workspace Agent.xcworkspace -scheme "Agent-iOS" -destination name="iPhone 14" -derivedDataPath="dd" clean test

    # - name: Run tvOS tests using only Xcode build.
    #   run: xcodebuild -workspace Agent.xcworkspace -scheme "Agent-tvOS" -destination name="Apple TV" -derivedDataPath="dd" clean test
    
    # - name: Run tests on iOS. (Using fastlane)
    #   run: bundle exec fastlane runIOSTests

    # - name: Archive iOS. (Using xcodebuild)
    #   run: xcodebuild clean archive -archivePath "archives/iOS.xcarchive" -configuration "Release" -workspace "Agent.xcworkspace" -scheme "Agent-iOS" -sdk "iphoneos" SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES 

    - name: Run tests and build NewRelic.xcframework (using fastlane)
      run: bundle exec fastlane testAndBuild

    - id: build
      name: Get name
      run: echo "::set-output name=version::$(cat fastlane/build_version)"

    # # In real GHA this step doesn't just output the zip file name, it uploads it to s3 as well.
    # - id: outputZippedName
    #   name: Print name
    #   run: echo "${{ steps.build.outputs.version }}"

    - uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        source:  ${{ steps.build.outputs.version }}
        destination: s3://nr-downloads-main/ios-v5/
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}